const { AndroidConfig, withAndroidManifest, withStringsXml } = require('@expo/config-plugins')

/**
 * Digital Asset Links — the app half.
 *
 * Declares that this app belongs to kingfishbets.com. The site half lives at
 * https://www.kingfishbets.com/.well-known/assetlinks.json (served by the
 * assetlinks route in kingfish-bets, from the ANDROID_CERT_SHA256 env var).
 * Chrome verifies BOTH directions before navigator.getInstalledRelatedApps()
 * will report this app, which is what lets the website stop showing a "Get it
 * on Google Play" card to someone who already installed it.
 *
 * There is no android/ directory in this repo — it is generated by prebuild —
 * so this has to be a config plugin rather than a hand edit that would be
 * wiped on the next build.
 *
 * Note this does NOT make the app open kingfishbets.com links. That would
 * additionally require an intent filter with autoVerify on the activity, and
 * the app deliberately has none: its deep links use the kingfish:// scheme.
 */

const SITE = 'https://www.kingfishbets.com'
const STRING_NAME = 'asset_statements'

const statement = JSON.stringify([
  {
    relation: ['delegate_permission/common.handle_all_urls'],
    target: { namespace: 'web', site: SITE },
  },
])

function withAssetStatementsString(config) {
  return withStringsXml(config, (cfg) => {
    cfg.modResults = AndroidConfig.Strings.setStringItem(
      [{ _: statement, $: { name: STRING_NAME, translatable: 'false' } }],
      cfg.modResults,
    )
    return cfg
  })
}

function withAssetStatementsMetaData(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      application,
      STRING_NAME,
      `@string/${STRING_NAME}`,
      'resource',
    )
    return cfg
  })
}

module.exports = function withAssetStatements(config) {
  return withAssetStatementsMetaData(withAssetStatementsString(config))
}
